- name: Update apt cache
  apt:
    update_cache: yes

- user:
    name: vagrant
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Install common packages
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - rsync
    - subversion
    - git
    - vim
    - curl
    - samba
    - samba-client
    - memcached
    - htop

- name: Ensure services are enabled and started
  service:
    name: "{{item}}"
    enabled: yes
    state: restarted
  with_items:
    - memcached
    - smbd

- name: Copy samba configuration in place.
  template:
    src: smb.conf
    dest: "/etc/samba/smb.conf"
    owner: root
    group: "root"
    mode: 0644

- name: Create Samba Password for User(s)
  shell: "(echo {{ item.smbpasswd }}; echo {{ item.smbpasswd }}) | smbpasswd -s -a {{ item.name }}"
  with_items:
    - { name: 'vagrant', smbpasswd: 'vagrant' }
