- name: Update apt cache
  apt:
    update_cache: yes

- apt_repository:
    repo: deb http://packages.dotdeb.org jessie all
    state: present

- apt_repository:
    repo: deb-src http://packages.dotdeb.org jessie all
    state: present

- name: Install PHP 5.6
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - php5
    - php5-cli
    - php5-common
    - php5-curl
    - php5-fpm
    - php5-xdebug
    - php5-xhprof
    - php5-mcrypt
    - php5-mysqlnd
    - php5-gearman
    - php5-imagick
    - php5-gd
    - php5-xsl
    - php5-geoip
    - php5-memcache
    - php5-memcached

- name: Copy php5-fpm configuration in place.
  template:
    src: www.conf
    dest: "/etc/php5/fpm/pool.d/www.conf"
    owner: root
    group: "root"
    mode: 0644

- name: Ensure services are enabled and started
  service:
    name: php5-fpm
    enabled: yes
    state: restarted

- user:
    name: vagrant
    shell: /bin/bash
    groups: www-data
    append: yes

- file:
    path: /home/vagrant/www/test
    owner: vagrant
    group: vagrant
    state: directory
    mode: 0775

- name: Copy default php script in place.
  template:
    src: index.php
    dest: "/home/vagrant/www/test/index.php"
    owner: vagrant
    group: vagrant
    mode: 0644

- name: Copy default user nginx configuration in place.
  template:
    src: test.conf
    dest: "/home/vagrant/nginx/test.conf"
    owner: vagrant
    group: vagrant
    mode: 0644

- name: composer install
  shell: >
      curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
