- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: nginx

- name: Copy nginx configuration in place.
  template:
    src: nginx.conf
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644

- file:
    path: /home/vagrant/www
    owner: vagrant
    group: vagrant
    state: directory
    mode: 0775

- file:
    path: /home/vagrant/nginx
    owner: vagrant
    group: vagrant
    state: directory
    mode: 0775

- file:
    path: /home/vagrant/logs
    owner: vagrant
    group: vagrant
    state: directory
    mode: 0775

- name: Ensure services are enabled and started
  service:
    name: nginx
    enabled: yes
    state: restarted
